# mosquitto/config/mosquitto.conf

# Escuchar en el puerto estándar MQTT en todas las interfaces de red
listener 1883

listener 9001
protocol websockets


# Permitir conexiones sin usuario/contraseña (ideal para pruebas en red local)
allow_anonymous true