version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

  reconocimiento:
    build: .
    container_name: reconocimiento_facial
    depends_on:
      - mosquitto
    restart: always
    ports:
      - "5000:5000"
    environment:
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
      - MQTT_TOPIC=test/#
    volumes:
      - ./imagenes:/app/imagenes
      - ./rostros:/app/rostros
      - ./data:/app/data